# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-test-app"
client_id = "1d091947ed212a61d22d53144a5f4859"
application_url = "https://ap-set-mp-fate.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ap-set-mp-fate.trycloudflare.com/auth/callback",
  "https://ap-set-mp-fate.trycloudflare.com/auth/shopify/callback",
  "https://ap-set-mp-fate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
